### ISSUE TITLE
Add ID & details page url

### ISSUE THREAD

**Issue by RuudBurger** [rarbg/torrentapi#4]
The info_page key now returns an URL with the token inside. This way I can't cache it properly because it expires soon. Is there a way to either return the torrent ID so I can create the detail URL of the release myself, or return the actual page url. Either way it's fine by me ;)
So I need `https://rarbg.to/torrent/XXXXX` or just the `XXXXX` part.

https://github.com/RuudBurger/CouchPotatoServer/issues/5318 & https://github.com/RuudBurger/CouchPotatoServer/blob/master/couchpotato/core/media/_base/providers/torrent/rarbg.py

**Comment by rarbg** [comment]
Im sorry but there is no way to make the link with a persistent token due to multiple copyright reasons... however you can cache the link without token , as soon as i is clicked / displayed call  'token': 'https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato', and append the new token to the request

**Comment by ne0ark** [comment]
Is it possible to get a IMDB link also when doing searchs by string?

**Comment by rarbg** [comment]
@ne0ark what project are you from ? why didnt you read the docs ? what searches exactly are you performing ( what urls are you calling ) that dont give you imdb ? why are you hijacking this issue instead of opening a new one ?

**Comment by turbalf** [comment]
Hello,
Will the solution given by RARBG be coded in a future update ?
Thanks a lot both of you for your work !
