### ISSUE TITLE
Search by tvdb number don't show all the result

### ISSUE THREAD

**Issue by pingoo78** [rarbg/torrentapi#7]
Hello,

I see a little bug when i search torrent with the tvdb number.
I don't see all result.

An exemple with x-files :

When I go to :
`http://torrentapi.org/pubapi_v2.php?sort=last&search_string=x-files&search_tvdb=77398&mode=search&format=json_extended&ranked=0&token=XXXXX`

I don't see the new season 10.

When I remove the 'search_tvdb' option :
`http://torrentapi.org/pubapi_v2.php?sort=last&search_string=x-files&mode=search&format=json_extended&ranked=0&token=XXXXX`

I see the new season 10. And in the json_extended information, I can see the same tvdb number "tvdb":"77398"

Thank for your help ;)

**Comment by rarbg** [comment]
Hello @pingoo78 
Can you tell me from which project are you ?

**Comment by rarbg** [comment]
1. You dont need search_string AND tvdb , only one of those :)
2.
I can confirm that this is a bug and this is related to how the API was planned but it wont be fixed soon because this is a single case.
The issue is that 
The old x-files has imdb tt0106179
The new x-files has imdb tt4370492
Both have the SAME tvdb.
Because all api calls are retranslated internally in our api to imdb its bascally working only for the old x-files.

**Comment by rarbg** [comment]
@romanvm
This should be related to your question.
What urls are you calling ?

**Comment by pingoo78** [comment]
@rarbg I use sickrage ;)

**Comment by romanvm** [comment]
@rarbg I see now. I didn't know about the difference and used the IMDB ID obtained from TVDB metadata (they contain the old one), not from rarbg. I guess I need to fix my code. Thanks for pointing this out.

**Comment by pingoo78** [comment]
@rarbg it seems imdb change their website today because the new x-files imdb number tt4370492 redirects now to the old x-files imdb number tt0106179

**Comment by rarbg** [comment]
@pingoo78 @romanvm 
You had no idea what kind of operations i had to do to fix the imdb change.
But its fixed and tested.
So please confirm ? :)

**Comment by pingoo78** [comment]
Yes it's good now :)
Thanks for your help.
