### ISSUE TITLE
any plans to make compatible with popcorn time?

### ISSUE THREAD

**Issue by dmsherazi** [rarbg/torrentapi#8]

**Comment by rarbg** [comment]
none. popcorntime should integrate us , not the other way around. there are already 20 apps  integrated with the current api and i dont see why popcorntime cant integrate to it instead of us to them.

**Comment by Hellowlol** [comment]
Is you take a look at the popcorns api source code it uses the site to parse the info (Eztv). Here they get a real api to work it. All you need to do is make a wrapper.

**Comment by rarbg** [comment]
Hes talking about the yts clown api :)
Because they currently use the site to search they just get banned because they havent implemented the api. Now because @dmsherazi doesnt want to implement a simple 50 liner after me posting that they should move to the api he decided to open an issue for us to change our api to accustomize them :) which is never going to happen.
